"""Create a ZIP whose contents can be extracted directly into the public directory."""
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit
import hashlib
import json
import zipfile

ROOT = Path(__file__).resolve().parent


class Dependencies(HTMLParser):
    def __init__(self):
        super().__init__()
        self.paths = {Path('index.html')}

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        url = attrs.get('src') if tag == 'script' else (
            attrs.get('href') if tag == 'link' and attrs.get('rel') == 'stylesheet' else None)
        if url:
            parsed = urlsplit(url)
            if not parsed.scheme and not parsed.netloc:
                self.paths.add(Path(parsed.path))


def build():
    deps = Dependencies()
    deps.feed((ROOT / 'index.html').read_text(encoding='utf-8'))
    paths = set(deps.paths) | {Path('.htaccess'), Path('manifest.webmanifest'), Path('sw.js')}
    for folder in ['assets', 'output/audio', 'output/pdf']:
        paths.update(p.relative_to(ROOT) for p in (ROOT / folder).rglob('*') if p.is_file())
    paths.add(Path('output/gitarska_pustolovina.html'))
    offline = sorted(path for path in paths if path.parts[0] != 'output' and path.name not in {'.htaccess', 'sw.js'})
    digest = hashlib.sha256()
    for relative in offline:
        digest.update(relative.as_posix().encode())
        digest.update((ROOT / relative).read_bytes())
    digest.update((ROOT / 'sw.js').read_bytes())
    (ROOT / 'cache-list.js').write_text(
        '// Generated by build_hosting.py; regenerate after changing app files.\n'
        + 'const OFFLINE_VERSION=' + json.dumps(digest.hexdigest()[:16]) + ';\n'
        + 'const OFFLINE_FILES=' + json.dumps([path.as_posix() for path in offline], ensure_ascii=False) + ';\n',
        encoding='utf-8')
    paths.add(Path('cache-list.js'))
    for relative in paths:
        if not (ROOT / relative).is_file():
            raise FileNotFoundError(relative)
    target = ROOT / 'dist' / 'mare-guitar-app-public.zip'
    target.parent.mkdir(exist_ok=True)
    with zipfile.ZipFile(target, 'w', zipfile.ZIP_DEFLATED) as archive:
        for relative in sorted(paths):
            archive.write(ROOT / relative, relative.as_posix())
    with zipfile.ZipFile(target) as archive:
        assert archive.testzip() is None, 'Archive integrity check failed'
        assert 'index.html' in archive.namelist(), 'Missing root index.html'
        for relative in paths:
            assert archive.read(relative.as_posix()) == (ROOT / relative).read_bytes(), relative
    print(f'ZIP: {target}')
    print(f'Files: {len(paths)}; bytes: {target.stat().st_size}')
    print(f'SHA256: {hashlib.sha256(target.read_bytes()).hexdigest()}')


if __name__ == '__main__':
    build()
