/* Song pages and child-friendly explanations; no network dependencies. */
window.GuitarSongUI=(()=>{
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const help=(label,kind,attrs='')=>`<button type="button" class="data-help" data-explain="${kind}" ${attrs}>${label}</button>`;
  const duration=d=>d===.5?'½':d===1.5?'1½':String(d);
  const svgButton=(body,kind,attrs,label)=>`<g role="button" tabindex="0" data-explain="${kind}" ${attrs} aria-label="${esc(label)}" class="svg-help">${body}</g>`;
  function row(song,notes,r,shift){
    const strings=[...new Set(song.rows.flat().map(n=>n[0]))].sort();
    const short=notes.length<=4,width=short?268:1030,endX=width-10,space=endX-55;
    const lyrics=notes.some(n=>n[3]);const lastY=80+(strings.length-1)*64,height=lyrics?lastY+84:lastY+36;
    const weights=notes.map(n=>.75+n[2]*.25),total=weights.reduce((a,b)=>a+b,0);let cursor=0,beats=0;
    const staff=strings.map((s,i)=>`<line x1="55" y1="${80+i*64}" x2="${endX}" y2="${80+i*64}" class="tab-line" data-string="${s}"/><text x="4" y="${87+i*64}" class="print-string">${s}. ž.</text>`).join('');
    const labels=strings.map((s,i)=>`<button type="button" class="tab-string-fixed" style="top:${(80+i*64)/height*100}%" data-explain="string" data-string="${s}" aria-label="Što znači ${s}. žica?">${s}. žica</button>`).join('');
    const body=notes.map((n,i)=>{
      const start=55+space*cursor/total,end=55+space*(cursor+weights[i])/total,x=(start+end)/2,y=80+strings.indexOf(n[0])*64;
      const attrs=`data-string="${n[0]}" data-fret="${n[1]+shift}" data-duration="${n[2]}"`;
      const fret=svgButton(`<rect x="${x-22}" y="${y-22}" width="44" height="44" rx="5"/><text x="${x}" y="${y+7}" class="tab-fret">${n[1]+shift}</text>`,'fret',attrs,`Objasni prag ${n[1]+shift} na ${n[0]}. žici`);
      const timing=svgButton(`<rect x="${x-22}" y="0" width="44" height="44" fill="transparent"/><text x="${x}" y="28" class="tab-duration">${duration(n[2])}</text>`,'duration',attrs,`Trajanje ${duration(n[2])} koraka`);
      const text=lyrics&&n[3]?svgButton(`<rect x="${x-22}" y="${lastY+30}" width="44" height="44" fill="transparent"/><text x="${x}" y="${lastY+58}" class="tab-lyric">${esc(n[3])}</text>`,'lyric',`${attrs} data-lyric="${esc(n[3])}"`,`Slog ${n[3]} ispod tona`):'';
      cursor+=weights[i];beats+=n[2];const meter=song.barBeats||4;
      const bar=Math.abs(beats/meter-Math.round(beats/meter))<.001&&i<notes.length-1?svgButton(`<rect x="${end-7}" y="22" width="14" height="${lastY-12}" fill="transparent"/><line x1="${end}" y1="25" x2="${end}" y2="${lastY+9}" class="tab-bar"/>`,'bar',`data-meter="${meter}"`,'Uspravna crta između glazbenih dijelova'):'';
      return `<g class="tab-note" data-song-note="${song.id}-${r}-${i}">${fret}${timing}${text}</g>${bar}`;
    }).join('');
    return `${song.rowLabels?.[r]?`<h3 class="song-row-label">${esc(song.rowLabels[r])}</h3>`:''}<div class="tab-row"><div class="tab-string-labels">${labels}</div><div class="compact-tab-scroll"><svg class="compact-tab${short?' short-tab':''}" viewBox="0 0 ${width} ${height}" role="group" aria-label="${esc(song.title)}, red ${r+1}. Dodirni oznaku za objašnjenje.">${staff}${body}</svg></div></div>`;
  }
  function render(id,shift,tempo){
    const songs=window.GUITAR_SONGS,song=songs.find(s=>s.id===id);
    if(song?.lesson||song?.hidden)shift=0;
    if(!song){
      const tiles=(category,lesson=false)=>songs.filter(s=>!s.hidden&&(lesson?!!s.lesson:!s.lesson&&(s.category==='bozic')===category)).map(s=>`<a class="song-choice" href="#pjesmica/${s.id}"><div class="card-tag">${s.lesson?'ISTO KAO U LEKCIJAMA':Math.max(...s.rows.flat().map(n=>n[1]))>3?'ZA POSLIJE · UZ ODRASLU OSOBU':'JOŠ JEDNA PJESMICA'}</div><h2>${esc(s.title)} →</h2><p>${s.lesson?'Dijelovi A i B · ista mjesta za prste':s.rows.length===1?'Jedan red zvukova':'Sviraj jedan red po jedan'}</p></a>`).join('');
      return `<div class="page-heading"><div><div class="eyebrow">ODABERI PJESMICU</div><h1>Moje pjesmice</h1><p class="lede">Za vježbe u trećem i četvrtom tjednu otvori prvu karticu.</p></div></div><h2>Vježba iz lekcija</h2><div class="grid song-choices">${tiles(false,true)}</div><h2>Još poznatih pjesmica</h2><div class="grid song-choices">${tiles(false)}</div><h2 class="christmas-heading">Božićne pjesmice</h2><div class="grid song-choices">${tiles(true)}</div>`;
    }
    const meter=song.barBeats||4;
    const settings=`<details class="song-options"><summary>Brzina i više mogućnosti</summary><div class="song-controls">${!song.lesson&&!song.hidden?`<label for="song-position">${help('Gdje sviram','position')}<select id="song-position" aria-label="Gdje sviram"><option value="0"${shift===0?' selected':''}>Osnovno — niže</option><option value="2"${shift===2?' selected':''}>Dva praga više — više</option></select></label>`:''}<label for="song-tempo">${help('Brzina','tempo',`data-tempo="${tempo}"`)}<select id="song-tempo" aria-label="Brzina">${[50,60,75].map(v=>`<option value="${v}"${tempo===v?' selected':''}>${v===50?'Polako':v===60?'Mirno':'Brže'}</option>`).join('')}</select></label></div><div class="song-meta">${help(esc(song.tag),'scope',`data-song="${song.id}"`)}${help(`${song.rows.flat().length} tonova`,'count',`data-count="${song.rows.flat().length}"`)}${help(`Brojimo po ${meter}`,'bar',`data-meter="${meter}"`)}</div></details>`;
    const level=song.id==='bratec'?'<p class="song-level">Cijela pjesmica za poslije · drugi položaj. <a href="#pjesmica/bratec-vjezba">Otvori vježbu iz lekcija</a>.</p>':!song.lesson&&Math.max(...song.rows.flat().map(n=>n[1]))>3?'<p class="song-level">Za poslije · probaj uz odraslu osobu.</p>':'';
    const legend=`<div class="song-legend basic-legend" aria-label="Kako čitam brojeve">${help('Crta = žica','string','data-string="1"')} ${help('Broj = prag','fret','data-string="1" data-fret="1"')} ${help('0 = bez prsta','fret','data-string="1" data-fret="0"')} ${help('Mali broj = trajanje','duration','data-duration="1"')}</div>`;
    return `<div class="page-heading song-heading"><div><a class="song-back" href="#pjesmica">Sve pjesmice</a><h1>${esc(song.title)}</h1>${level}<p class="tune-check">Je li gitara naštimana?</p></div></div><section class="sheet song-sheet"><article class="song primary-song" id="${song.id}"><div class="song-title"><button type="button" class="button song-play" data-play-song="${song.id}">▶ Slušaj me</button>${help('Kako slušam?','listen')}</div><p class="tap-hint">Dodirni broj ako trebaš pomoć.${song.lesson?' Sviraj jedan mali dio odjednom.':' Povuci zapis lijevo ili desno.'}</p>${legend}${song.rows.map((n,r)=>row(song,n,r,shift)).join('')}${song.description?`<p class="song-tip">${esc(song.description)}</p>`:''}</article>${settings}<details class="song-sources"><summary>Za odrasle: izvor</summary><p>Vlastiti početnički raspored melodije. <a href="${song.source||'https://imslp.org/wiki/Fr%C3%A8re_Jacques_(Rameau,_Jean-Philippe)'}">Notni izvor</a>. ${song.lesson?'Ista mjesta za prste kao u lekcijama.':song.id==='bratec'?'Puni zapis koristi drugi položaj od vježbe iz lekcija.':''}</p></details><p class="print-row"><button type="button" class="print print-quiet">Ispiši listić</button></p></section>`;
  }
  function neck(string,fret){
    const frets=fret>3?[fret-1,fret,fret+1]:[1,2,3];const start=frets[0]-1;const target=fret?120+(fret-start)*95-14:90;
    return `<svg class="modal-picture" viewBox="0 0 450 245" role="img" aria-label="${string}. žica, ${fret?'prag '+fret:'bez pritiska'}"><rect x="120" y="48" width="285" height="158" rx="7" fill="#eef4ef"/>${frets.map((f,i)=>`<text x="${132+i*95}" y="30" font-size="15">${f}. prag</text><line x1="${215+i*95}" y1="48" x2="${215+i*95}" y2="205" stroke="#788d84"/>`).join('')}${Array.from({length:6},(_,i)=>`<text x="20" y="${67+i*25}" font-size="15">${i+1}. žica</text><line x1="120" y1="${62+i*25}" x2="405" y2="${62+i*25}" stroke="${i+1===string?(string===1?'#ec407a':'#e69100'):'#aab8b0'}" stroke-width="${i+1===string?4:1}"/>`).join('')}<circle cx="${target}" cy="${62+(string-1)*25}" r="11" fill="#e9b65f"/><text x="120" y="232" font-size="14">${fret?'Žuta točka: ovdje pritisni jagodicom.':'Prazna žica: lijeva ruka ne pritišće.'}</text></svg>`;
  }
  function steps(d){
    const count=Math.ceil(d);const units=Array.from({length:count},(_,i)=>{const fraction=Math.min(1,d-i);return `<circle cx="${55+i*70}" cy="58" r="24" fill="${fraction===1?'#39796c':'#eef4ef'}" stroke="#39796c" stroke-width="2"/>${fraction<1?`<path d="M ${55+i*70} 34 A 24 24 0 0 1 ${55+i*70} 82 Z" fill="#39796c"/>`:''}<text x="${55+i*70}" y="108" text-anchor="middle" font-size="16">${fraction<1?'½':i+1}</text>`}).join('');
    return `<svg class="modal-picture" viewBox="0 0 350 125" role="img" aria-label="${duration(d)} glazbenih koraka">${units}</svg>`;
  }
  let trigger=null;
  function explain(el){
    trigger=el;const a=el.dataset,type=a.explain;const s=Number(a.string||1),f=Number(a.fret||0),d=Number(a.duration||1);let title='',text='',picture='',task='';
    if(type==='fret'){title=f?`Žica ${s}, prag ${f}`:'Nula: žica svira slobodno';text=f?`Prag je mjesto za prst. Pronađi ${s}. žicu, pa ${f}. metalnu prečku. Jagodicu stavi tik uz nju, s njezine strane prema glavi gitare. Zatim drugom rukom nježno odsviraj tu žicu.`:`Broj 0 znači: nemoj pritiskati žicu lijevom rukom. Drugom rukom odsviraj ${s}. žicu. Ona već ima svoj zvuk!`;picture=neck(s,f);task='Probaj jednom polako. Zatim opusti šaku.';}
    else if(type==='string'){title=`${s}. žica je tvoj put`;text=`Gitara ima šest žica. Prva je najtanja i u položaju za sviranje najbliža podu; druga je odmah uz nju. Na našoj karti prva je gornja crta. Kad broj stoji na crti ${s}. žice, sviraj baš tu žicu.`;picture=neck(s,0);task='Pronađi žicu na gitari i nježno je dotakni.';}
    else if(type==='duration'){title=`Zvuk traje ${duration(d)} ${d===1?'korak':'koraka'}`;text=d===.5?'Ovo je pola glazbenog koraka. Dva kratka zvuka stanu u jedan korak: „ta-ti”.':d===1.5?'Zadrži zvuk jedan cijeli korak i još pola sljedećeg. To je 1½.':`Odsviraj samo jednom, a zvuk neka ostane dok napraviš ${d} ravnomjernih glazbenih koraka. Ne trzaj ponovno na svaki korak.`;picture=steps(d);task='Najprije pokaži trajanje pljeskanjem ili brojanjem.';}
    else if(type==='lyric'){title=`Pjevamo slog „${a.lyric||'Bra-'}”`;text='Tekst je ispod zvuka uz koji ga pjevamo. Crtica na kraju sloga kaže da riječ još nije gotova: „Bra-” i „tec” zajedno su „Bratec”. Kad ispod sljedećeg tona nema novog sloga, nastavi isti slog.';picture='<div class="syllable-picture"><span>Bra-</span><span>tec</span><b>Bratec</b></div>';task='Otpjevaj slog, pa odsviraj broj točno iznad njega.';}
    else if(type==='bar'){const m=Number(a.meter||4);title='Mala ograda za glazbene korake';text=`Uspravna crta dijeli glazbu u male skupine koje zovemo taktovi. Ovdje brojimo ${Array.from({length:m},(_,i)=>i+1).join(', ')} pa ponovno od 1. Crta ne znači stani: nastavi svirati u istom koraku.`;picture=steps(m);task='Izbroji jednu skupinu, pa odmah kreni u sljedeću.';}
    else if(type==='position'){title='Ista pjesma, viši glas';text='Kad sve brojeve povećamo za 2, isti oblik melodije putuje dva praga prema tijelu gitare. Nula tada postaje 2, a 3 postaje 5. Pjesma se i dalje prepoznaje, ali zvuči više.';picture='<div class="position-picture"><span>0 → 2</span><span>3 → 5</span><b>isti put · viši zvuk</b></div>';task='Poslušaj osnovni položaj, zatim položaj dva praga više.';}
    else if(type==='tempo'){title='Koliko brzo korača glazba?';text=`Izaberi „Polako” da stigneš pronaći svako mjesto za prst. Kad ti ide lako, možeš probati brže. Ne moraš žuriti.`;picture=steps(3);task='Najprije polako i čisto. Brzinu dodaj poslije.';}
    else if(type==='count'){title=`${a.count} malih zvukova`;text='Ovaj broj govori koliko puta odsviramo ton u ovom zapisu. Ako se isti broj praga ponovi, opet ga odsviraj. Trajanje jednog tona može biti kratko ili dugo.';picture=steps(3);task='Prstom pokaži tri broja zaredom.';}
    else if(type==='listen'){title='Poslušaj pa odgovori';text='Prvo čuješ dva kratka otkucaja. Zatim slijedi melodija, a žuto mjesto pokazuje koji ton upravo svira. Zvuk je napravljen računalom. Možeš samo slušati ili polako svirati zajedno.';picture=steps(2);task='Najprije poslušaj jedan red, pa ga pokušaj ponoviti.';}
    else {const song=window.GUITAR_SONGS.find(s=>s.id===a.song);title=song?.title||'Naša pjesmica';text=type==='scope'?`Oznaka kaže što učimo: ${song?.tag.toLowerCase()}. Jedna žica znači jedan put; dvije žice znače da ponekad prijeđemo na susjedni put. „Početak” ili „dio refrena” znači da još ne sviramo cijelu pjesmu.`:song?.description||'Otvori kartu pjesme i prati brojeve slijeva nadesno. Svaki broj govori gdje staviti prst.';picture=neck(1,0);task='Najprije probaj jedan red, pa odmori ruku.';}
    const link=window.withFingers||(s=>s);
    document.getElementById('explain-body').innerHTML=`<div class="sheet-label">ZVONKO OBJAŠNJAVA</div><h2 id="explain-title">${esc(title)}</h2>${picture}<p>${link(esc(text))}</p><div class="note note-playful">${link(esc(task))}</div>`;
    document.getElementById('explain-dialog').showModal();
  }
  const showHelp=(body,el)=>{trigger=el;document.getElementById('explain-body').innerHTML=body;document.getElementById('explain-dialog').showModal();};
  const close=()=>{const d=document.getElementById('explain-dialog');d.close();if(trigger?.isConnected)trigger.focus({preventScroll:true});};
  document.addEventListener('click',e=>{if(e.target.closest('#explain-dialog .modal-close,#explain-dialog .modal-done'))close();const dialog=document.getElementById('explain-dialog');if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
  document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.svg-help')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
  return {render,explain,showHelp};
})();
