/* Song pages and child-friendly explanations; no network dependencies. */
window.GuitarSongUI=(()=>{
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const help=(label,kind,attrs='')=>`<button type="button" class="data-help" data-explain="${kind}" ${attrs}>${label}</button>`;
  const duration=d=>d===.5?'½':d===1.5?'1½':String(d);
  const svgButton=(body,kind,attrs,label)=>`<g role="button" tabindex="0" data-explain="${kind}" ${attrs} aria-label="${esc(label)}" class="svg-help">${body}</g>`;
  function row(song,notes,r,shift){
    const strings=[...new Set(song.rows.flat().map(n=>n[0]))].sort();
    const lyrics=notes.some(n=>n[3]);const lastY=34+(strings.length-1)*23,height=lyrics?lastY+38:lastY+18;
    const weights=notes.map(n=>.75+n[2]*.25),total=weights.reduce((a,b)=>a+b,0);let cursor=0,beats=0;
    const staff=strings.map((s,i)=>svgButton(`<rect x="0" y="${20+i*23}" width="51" height="25" fill="transparent"/><text x="4" y="${40+i*23}" class="tab-string">${s}. ž.</text>`,'string',`data-string="${s}"`,`Što znači ${s}. žica?`)+`<line x1="55" y1="${34+i*23}" x2="1020" y2="${34+i*23}" class="tab-line" data-explain="string" data-string="${s}"/>`).join('');
    const body=notes.map((n,i)=>{
      const start=55+965*cursor/total,end=55+965*(cursor+weights[i])/total,x=(start+end)/2,y=34+strings.indexOf(n[0])*23;
      const attrs=`data-string="${n[0]}" data-fret="${n[1]+shift}" data-duration="${n[2]}"`;
      const fret=svgButton(`<rect x="${x-17}" y="${y-14}" width="34" height="27" rx="5"/><text x="${x}" y="${y+7}" class="tab-fret">${n[1]+shift}</text>`,'fret',attrs,`Objasni prag ${n[1]+shift} na ${n[0]}. žici`);
      const timing=svgButton(`<rect x="${x-17}" y="0" width="34" height="20" fill="transparent"/><text x="${x}" y="14" class="tab-duration">${duration(n[2])}</text>`,'duration',attrs,`Trajanje ${duration(n[2])} koraka`);
      const text=lyrics&&n[3]?svgButton(`<rect x="${x-23}" y="${lastY+12}" width="46" height="26" fill="transparent"/><text x="${x}" y="${lastY+29}" class="tab-lyric">${esc(n[3])}</text>`,'lyric',`${attrs} data-lyric="${esc(n[3])}"`,`Slog ${n[3]} ispod tona`):'';
      cursor+=weights[i];beats+=n[2];const meter=song.barBeats||4;
      const bar=Math.abs(beats/meter-Math.round(beats/meter))<.001&&i<notes.length-1?svgButton(`<rect x="${end-7}" y="22" width="14" height="${lastY-12}" fill="transparent"/><line x1="${end}" y1="25" x2="${end}" y2="${lastY+9}" class="tab-bar"/>`,'bar',`data-meter="${meter}"`,'Uspravna crta između glazbenih dijelova'):'';
      return `<g class="tab-note" data-song-note="${song.id}-${r}-${i}">${fret}${timing}${text}</g>${bar}`;
    }).join('');
    return `<div class="compact-tab-scroll"><svg class="compact-tab" viewBox="0 0 1030 ${height}" role="group" aria-label="${esc(song.title)}, red ${r+1}. Klikni oznaku za objašnjenje.">${staff}${body}</svg></div>`;
  }
  function render(id,shift,tempo){
    const songs=window.GUITAR_SONGS,song=songs.find(s=>s.id===id);
    if(!song){
      const tiles=category=>songs.filter(s=>(s.category==='bozic')===category).map(s=>`<article class="song-choice"><div class="card-tag">${esc(s.tag)}</div><h2><a href="#pjesmica/${s.id}">${esc(s.title)} →</a></h2><p>${s.rows.flat().length} tonova · ${s.rows.length} reda tabulature</p></article>`).join('');
      return `<div class="page-heading"><div><div class="eyebrow">ODABERI PJESMICU</div><h1>Moje pjesmice</h1><p class="lede">Klikni pjesmicu koju želiš vježbati. Brojevi izgledaju čudno? Dodirni ih — reći ću ti priču!</p></div></div><h2>Poznate melodije</h2><div class="grid song-choices">${tiles(false)}</div><h2 class="christmas-heading">Božićne pjesmice</h2><div class="grid song-choices">${tiles(true)}</div>`;
    }
    const meter=song.barBeats||4;
    const tuneNote=`<aside class="tune-reminder" role="note"><p><strong>Prvo naštimaj gitaru.</strong> Mama ili tata polako okreću mehanike na glavi. Ti nježno odsviraš jednu praznu žicu.</p><a href="#pocetak/stimanje">Kako se štima →</a></aside>`;
    return `<div class="page-heading song-heading"><div><a class="song-back" href="#pjesmica">← Sve pjesmice</a><h1>${help(esc(song.title),'song',`data-song="${song.id}"`)}</h1></div></div>${tuneNote}<section class="sheet song-sheet"><div class="song-meta">${help(esc(song.tag),'scope',`data-song="${song.id}"`)}${help(`${song.rows.flat().length} tonova`,'count',`data-count="${song.rows.flat().length}"`)}${help(`Brojimo po ${meter}`,'bar',`data-meter="${meter}"`)}</div><div class="song-controls"><label for="song-position">${help('Gdje sviram ⓘ','position')} <select id="song-position"><option value="0"${shift===0?' selected':''}>Osnovno — niže</option><option value="2"${shift===2?' selected':''}>Dva praga više — više</option></select></label><label for="song-tempo">${help('Brzina ⓘ','tempo',`data-tempo="${tempo}"`)} <select id="song-tempo">${[50,60,75].map(v=>`<option value="${v}"${tempo===v?' selected':''}>${v===50?'Polako':v===60?'Mirno':'Brže'} · ${v}</option>`).join('')}</select></label><button id="stop-song" type="button" class="secondary" disabled>■ Stani</button></div><div class="song-legend">${help('Crta = žica','string','data-string="1"')} · ${help('Broj = prst','fret','data-string="1" data-fret="3"')} · ${help('0 = prazno','fret','data-string="1" data-fret="0"')} · ${help('Mali broj = koliko traje','duration','data-duration="1"')} · ${help('Riječ ispod = pjevaš','lyric','data-lyric="Bra-"')}</div><p class="tap-hint">Dodirni bilo što na crtežu kad zapne — objasnit ću ti! Na mobitelu povuci tabulaturu lijevo-desno.</p><article class="song primary-song" id="${song.id}"><div class="song-title"><p class="shift-caption">${shift?'Svi tonovi su malo više na vratu.':'Sviramo u osnovnom položaju.'}</p><div><button type="button" class="secondary song-play" data-play-song="${song.id}">▶ Slušaj me</button> ${help('ⓘ','listen')}</div></div>${song.rows.map((n,r)=>row(song,n,r,shift)).join('')}${song.description?`<p class="song-tip">${esc(song.description)}</p>`:''}</article><p class="song-footnote">Idi s lijeva na desno, red po red. Polako i lijepo — brzina dolazi kasnije!</p><details class="song-sources"><summary>Za odrasle: izvor</summary><p>Vlastiti početnički raspored melodije. <a href="${song.source||'https://imslp.org/wiki/Fr%C3%A8re_Jacques_(Rameau,_Jean-Philippe)'}">Notni izvor</a>. ${song.id==='bratec'?'Motiv iz trećeg tjedna u C-duru.':''}</p></details><p class="print-row"><button type="button" class="print print-quiet">Ispiši listić</button></p></section>`;
  }
  function neck(string,fret){
    const frets=fret>3?[fret-1,fret,fret+1]:[1,2,3];const start=frets[0]-1;const target=fret?120+(fret-start)*95-14:90;
    return `<svg class="modal-picture" viewBox="0 0 450 245" role="img" aria-label="${string}. žica, ${fret?'prag '+fret:'bez pritiska'}"><rect x="120" y="48" width="285" height="158" rx="7" fill="#eef4ef"/>${frets.map((f,i)=>`<text x="${132+i*95}" y="30" font-size="15">${f}. prag</text><line x1="${215+i*95}" y1="48" x2="${215+i*95}" y2="205" stroke="#788d84"/>`).join('')}${Array.from({length:6},(_,i)=>`<text x="20" y="${67+i*25}" font-size="15">${i+1}. žica</text><line x1="120" y1="${62+i*25}" x2="405" y2="${62+i*25}" stroke="${i+1===string?'#39796c':'#aab8b0'}" stroke-width="${i+1===string?4:1}"/>`).join('')}<circle cx="${target}" cy="${62+(string-1)*25}" r="11" fill="#e9b65f"/><text x="120" y="232" font-size="14">${fret?'Žuta točka: ovdje pritisni jagodicom.':'Prazna žica: lijeva ruka ne pritišće.'}</text></svg>`;
  }
  function steps(d){
    const count=Math.ceil(d);const units=Array.from({length:count},(_,i)=>{const fraction=Math.min(1,d-i);return `<circle cx="${55+i*70}" cy="58" r="24" fill="${fraction===1?'#39796c':'#eef4ef'}" stroke="#39796c" stroke-width="2"/>${fraction<1?`<path d="M ${55+i*70} 34 A 24 24 0 0 1 ${55+i*70} 82 Z" fill="#39796c"/>`:''}<text x="${55+i*70}" y="108" text-anchor="middle" font-size="16">${fraction<1?'½':i+1}</text>`}).join('');
    return `<svg class="modal-picture" viewBox="0 0 350 125" role="img" aria-label="${duration(d)} glazbenih koraka">${units}</svg>`;
  }
  let trigger=null;
  function explain(el){
    trigger=el;const a=el.dataset,type=a.explain;const s=Number(a.string||1),f=Number(a.fret||0),d=Number(a.duration||1);let title='',text='',picture='',task='';
    if(type==='fret'){title=f?`Žica ${s}, prag ${f}`:'Nula: žica svira slobodno';text=f?`Prag je mjesto za prst. Pronađi ${s}. žicu, pa ${f}. metalnu prečku. Jagodicu stavi tik uz nju, s njezine strane prema glavi gitare. Zatim drugom rukom nježno odsviraj tu žicu.`:`Broj 0 znači: nemoj pritiskati žicu lijevom rukom. Drugom rukom odsviraj ${s}. žicu. Ona već ima svoj zvuk!`;picture=neck(s,f);task='Probaj jednom polako. Zatim opusti šaku.';}
    else if(type==='string'){title=`${s}. žica je tvoj put`;text=`Gitara ima šest žica. Prva je najtanja i u položaju za sviranje najbliža podu; druga je odmah uz nju. Na našoj karti prva je gornja crta. Kad broj stoji na crti ${s}. žice, sviraj baš tu žicu.`;picture=neck(s,0);task='Pronađi žicu na gitari i nježno je dotakni.';}
    else if(type==='duration'){title=`Zvuk traje ${duration(d)} ${d===1?'korak':'koraka'}`;text=d===.5?'Ovo je pola glazbenog koraka. Dva kratka zvuka stanu u jedan korak: „ta-ti”.':d===1.5?'Zadrži zvuk jedan cijeli korak i još pola sljedećeg. To je 1½.':`Odsviraj samo jednom, a zvuk neka ostane dok napraviš ${d} ravnomjernih glazbenih koraka. Ne trzaj ponovno na svaki korak.`;picture=steps(d);task='Najprije pokaži trajanje pljeskanjem ili brojanjem.';}
    else if(type==='lyric'){title=`Pjevamo slog „${a.lyric||'Bra-'}”`;text='Tekst je ispod zvuka uz koji ga pjevamo. Crtica na kraju sloga kaže da riječ još nije gotova: „Bra-” i „tec” zajedno su „Bratec”. Kad ispod sljedećeg tona nema novog sloga, nastavi isti slog.';picture='<div class="syllable-picture"><span>Bra-</span><span>tec</span><b>Bratec</b></div>';task='Otpjevaj slog, pa odsviraj broj točno iznad njega.';}
    else if(type==='bar'){const m=Number(a.meter||4);title='Mala ograda za glazbene korake';text=`Uspravna crta dijeli glazbu u male skupine koje zovemo taktovi. Ovdje brojimo ${Array.from({length:m},(_,i)=>i+1).join(', ')} pa ponovno od 1. Crta ne znači stani: nastavi svirati u istom koraku.`;picture=steps(m);task='Izbroji jednu skupinu, pa odmah kreni u sljedeću.';}
    else if(type==='position'){title='Ista pjesma, viši glas';text='Kad sve brojeve povećamo za 2, isti oblik melodije putuje dva praga prema tijelu gitare. Nula tada postaje 2, a 3 postaje 5. Pjesma se i dalje prepoznaje, ali zvuči više.';picture='<div class="position-picture"><span>0 → 2</span><span>3 → 5</span><b>isti put · viši zvuk</b></div>';task='Poslušaj osnovni položaj, zatim položaj dva praga više.';}
    else if(type==='tempo'){title='Koliko brzo korača glazba?';text=`Brzina govori koliko glazbenih koraka imamo u jednoj minuti. Pri brzini 60 jedan korak traje jednu sekundu. 50 je sporije, 75 je brže. Za početak izaberi miran tempo u kojem stižeš pronaći prstom svako mjesto.`;picture=steps(3);task='Najprije polako i čisto. Brzinu dodaj poslije.';}
    else if(type==='count'){title=`${a.count} malih zvukova`;text='Ovaj broj govori koliko puta odsviramo ton u ovom zapisu. Ako se isti broj praga ponovi, opet ga odsviraj. Trajanje jednog tona može biti kratko ili dugo.';picture=steps(3);task='Pokaži tri uzastopna broja u tabulaturi.';}
    else if(type==='listen'){title='Poslušaj pa odgovori';text='Prvo čuješ dva kratka otkucaja. Zatim slijedi melodija, a žuto mjesto pokazuje koji ton upravo svira. Zvuk je napravljen računalom. Možeš samo slušati ili polako svirati zajedno.';picture=steps(2);task='Najprije poslušaj jedan red, pa ga pokušaj ponoviti.';}
    else {const song=window.GUITAR_SONGS.find(s=>s.id===a.song);title=song?.title||'Naša pjesmica';text=type==='scope'?`Oznaka kaže što učimo: ${song?.tag.toLowerCase()}. Jedna žica znači jedan put; dvije žice znače da ponekad prijeđemo na susjedni put. „Početak” ili „dio refrena” znači da još ne sviramo cijelu pjesmu.`:song?.description||'Otvori kartu pjesme i prati brojeve slijeva nadesno. Svaki broj govori gdje staviti prst.';picture=neck(1,0);task='Uči jedan mali dio, a zatim poveži dijelove.';}
    document.getElementById('explain-body').innerHTML=`<div class="sheet-label">ZVONKO OBJAŠNJAVA</div><h2 id="explain-title">${esc(title)}</h2>${picture}<p>${esc(text)}</p><div class="note note-playful">${esc(task)}</div>`;
    document.getElementById('explain-dialog').showModal();
  }
  const close=()=>{const d=document.getElementById('explain-dialog');d.close();if(trigger?.isConnected)trigger.focus();};
  document.addEventListener('click',e=>{if(e.target.closest('.modal-close,.modal-done'))close();const dialog=document.getElementById('explain-dialog');if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
  document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.svg-help')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
  return {render,explain};
})();
